logging:
  file:
    name: logs/app.log

server:
  port: 8080

spring:
  application:
    name: RL-Job-Scheduler
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 599500
  sql:
      init:
        mode: always
        platform: mysql
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
mybatis-plus:
  configuration:
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

